AWSTemplateFormatVersion: 2010-09-09
Description: Provisioning of 2 EC2 Instances within a Custom Network via Cloudformation

Resources: 
  CFNUser:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
        - cloudformation
      LoginProfile: 
          Password: Ralph123ael.
      PasswordResetRequired: True

      ManagedPolicyArns: 
        - arn:aws:iam::*"
      #PermissionsBoundary: String
      Policies: 
        -   PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": "*",
                "Resource": "*"
            }
        ]
    }
            PolicyName: AdministratorFullAccess

      Tags: 
        - Name
      UserName: testprojectmanager
